// Code generated by Kitex v0.3.2. DO NOT EDIT.

package userservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/simplified-tiktok/kitex_gen/userdemo"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *userdemo.RegisterRequest, callOptions ...callopt.Option) (r *userdemo.RegisterResponse, err error)
	Login(ctx context.Context, req *userdemo.RegisterRequest, callOptions ...callopt.Option) (r *userdemo.RegisterResponse, err error)
	GetUserById(ctx context.Context, req *userdemo.GetUserRequest, callOptions ...callopt.Option) (r *userdemo.GetUserResponse, err error)
	Follow(ctx context.Context, req *userdemo.FollowRequest, callOptions ...callopt.Option) (r *userdemo.FollowResponse, err error)
	GetFollowList(ctx context.Context, req *userdemo.GetFollowListRequest, callOptions ...callopt.Option) (r *userdemo.GetFollowListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *userdemo.RegisterRequest, callOptions ...callopt.Option) (r *userdemo.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *userdemo.RegisterRequest, callOptions ...callopt.Option) (r *userdemo.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) GetUserById(ctx context.Context, req *userdemo.GetUserRequest, callOptions ...callopt.Option) (r *userdemo.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserById(ctx, req)
}

func (p *kUserServiceClient) Follow(ctx context.Context, req *userdemo.FollowRequest, callOptions ...callopt.Option) (r *userdemo.FollowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Follow(ctx, req)
}

func (p *kUserServiceClient) GetFollowList(ctx context.Context, req *userdemo.GetFollowListRequest, callOptions ...callopt.Option) (r *userdemo.GetFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowList(ctx, req)
}
